### ISSUE TITLE
Linux delivery is not working anymore

### ISSUE THREAD

**Issue by cvila84** [gemalto/helm-spray#4]
The executable name in plugin.yaml refers to kube-spray.exe which won't work under Linux.
We need need to handle the plugin.yaml file as a template and inject the right executable name according to the target (windows or linux)

**Comment by cvila84** [comment]
I am working on a PR to close this issue, but waiting for previous (https://github.com/gemalto/helm-spray/pull/3) to be closed so I can merge

**Comment by jroucheton** [comment]
@cvila84 PR (https://github.com/gemalto/helm-spray/pull/3) has been merged.

**Comment by cvila84** [comment]
Should fix https://github.com/gemalto/helm-spray/pull/5
Could you please issue v3.2.0 from this PR so I can integrate this version in https://github.com/gemalto/gokube (I also have a PR to submit here)
