### ISSUE TITLE
Implementation of "delete" mechanism

### ISSUE THREAD

**Issue by pamiel** [gemalto/helm-spray#8]
It could be interesting to have a deletion mechanism being implemented in `helm spray`, for a global deletion of all sub-charts of an umbrella chart, or for the individual deletion of a sub-chart (even if this one could be performed using a regular `helm delete` command).
Would need either to have a kind of `--delete` option, or to support "verbs" in the helm spray command line:
- `helm spray upgrade` (or `helm spray` without verb, for backward compatibility) for upgrading;
- `helm spray rollback` for rollback (see https://github.com/gemalto/helm-spray/issues/7);
- and `helm spray delete` for deletion of Releases...

**Comment by jroucheton** [comment]
**helm spray delete** is supported by the following helm plugin : 
* **helm-trash**: https://github.com/jroucheton/helm-trash
